# Tell Travis CI we're using PHP
language: php

# Using trusty instead of precise because we don't need PHP 5.2 or 5.3 anymore.
dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.jest-cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

install:
  - nvm install
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - export DIFF_HEAD=HEAD
  - source "$DEV_LIB_PATH/travis.install.sh"

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."

script:
  - npm run build:js
  - npm run build:css
  - source "$DEV_LIB_PATH/travis.script.sh"
  - |
    if [[ ! -z "$PHPUNIT_EXTRA_GROUP" ]]; then
      echo "Running phpunit group $PHPUNIT_EXTRA_GROUP"
      phpunit --verbose --group $PHPUNIT_EXTRA_GROUP
    fi

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  fast_finish: true
  # These need to be exact matches, including whitespace!
  allow_failures:
    # PHP unit tests (7.3, WordPress trunk)
    - env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1
    # PHP and JavaScript unit tests (7.3, WordPress trunk, with code coverage)
    - env: WP_VERSION=latest DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1 RUN_PHPUNIT_COVERAGE=1
    # PHP unit tests (7.4, WordPress trunk)
    - env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1
      php: 7.4snapshot
    # E2E tests, since flaky.
    - env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint,xmllint,phpsyntax,phpunit PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=
  include:
    - stage: test
    - name: PHP unit tests w/ external-http (7.3, WordPress latest)
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit                                INSTALL_PWA_PLUGIN=1 PHPUNIT_EXTRA_GROUP=external-http

    - name: PHP unit tests w/ external-http (5.6, WordPress 4.9)
      php: "5.6"
      env: WP_VERSION=4.9    DEV_LIB_ONLY=phpunit,phpsyntax                     PHPUNIT_EXTRA_GROUP=external-http
