name: AMP WP Github Release
description: Create or update the built zip for a GitHub release
inputs:
  repo-token:
    description: GitHub secret token
    required: true
  build-path:
    description: Path to built plugin
    required: true
outputs:
  branch:
    description: The git tag this action received
runs:
  using: node12
  main: dist/index.js
branding:
  icon: tag
  color: green
