name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source files
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        # Scripts are not ignored as they are needed to apply patches for the
        # `sabberworm/php-css-parser` dependency.
        run: composer install --prefer-dist --optimize-autoloader

      - name: Install Node dependencies
        # Prevent malicious scripts from being run with `--ignore-scripts`
        run: npm install --ignore-scripts

      - name: Run build script
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Install WP-CLI
        run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

      - name: Run PHP server via WP-CLI
        run: php wp-cli.phar server --allow-root &

      - name: Run Lighthouse CI health check
        run: lhci healthcheck

      - name: Run Lighthouse CI audit
        run: lhci collect --chrome-flags="--no-sandbox"

      - name: Assert Lighthouse CI measurements against requirements
        run: lhci assert

      - name: Upload Lighthouse CI measurements
        run: lhci upload

      - name: Terminate PHP server
        run: kill -s INT %1
